query SomaticAlterationsQuery {
  snvByGene: disease(efoId: "EFO_0000616") {
    id
    evidences(
      ensemblIds: ["ENSG00000171094"]
      enableIndirect: true
      size: 5
      datasourceIds: ["chop_gene_level_snv"]
    ) {
      count
      rows {
        dataset
        Disease
        frequencyInOverallDataset
        frequencyInPrimaryTumors
        frequencyInRelapseTumors
        geneFullName
        geneSymbol
        geneType
        MONDO
        OncoKBCancerGene
        OncoKBOncogeneTSG
        pedcbioPedotMutationsPlotURL
        pedcbioPedotOncoprintPlotURL
        proteinEnsemblId
        proteinRefseqId
        PMTL
        totalMutationsOverSubjectsInDataset
        totalPrimaryTumorsMutatedOverPrimaryTumorsInDataset
        totalRelapseTumorsMutatedOverRelapseTumorsInDataset
        diseaseFromSourceMappedId
        targetFromSourceId
        id
        score
      }
    }
  }

  cnvByGene: disease(efoId: "EFO_0000616") {
    id
    evidences(
      ensemblIds: ["ENSG00000171094"]
      enableIndirect: true
      size: 5
      datasourceIds: ["chop_gene_level_cnv"]
    ) {
      count
      rows {
        datasourceId
        dataset
        Disease
        frequencyInOverallDataset
        frequencyInPrimaryTumors
        frequencyInRelapseTumors
        geneFullName
        geneSymbol
        MONDO
        OncoKBCancerGene
        OncoKBOncogeneTSG
        PMTL
        totalAlterationsOverSubjectsInDataset
        totalPrimaryTumorsMutatedOverPrimaryTumorsInDataset
        totalRelapseTumorsMutatedOverRelapseTumorsInDataset
        variantCategory
        variantType
        datatypeId
        diseaseFromSourceMappedId
        targetFromSourceId
        id
        score
      }
    }
  }

  fusionByGene: disease(efoId: "EFO_0000616") {
    id
    evidences(
      ensemblIds: ["ENSG00000171094"]
      enableIndirect: true
      size: 5
      datasourceIds: ["chop_putative_oncogene_fused_gene"]
    ) {
      count
      rows {
        dataset
        Disease
        frequencyInOverallDataset
        frequencyInPrimaryTumors
        frequencyInRelapseTumors
        geneSymbol
        MONDO
        PMTL
        totalPrimaryTumorsMutatedOverPrimaryTumorsInDataset
        totalRelapseTumorsMutatedOverRelapseTumorsInDataset
        diseaseFromSourceMappedId
        targetFromSourceId
        totalAlterationsOverSubjectsInDataset
        id
        score
        diseaseFromSourceMappedId
      }
    }
  }

  fusion: disease(efoId: "EFO_0000616") {
    id
    evidences(
      ensemblIds: ["ENSG00000171094"]
      enableIndirect: true
      size: 5
      datasourceIds: ["chop_putative_oncogene_fusion"]
    ) {
      count
      rows {
        breakpointLocation
        dataset
        Disease
        frequencyInOverallDataset
        frequencyInPrimaryTumors
        frequencyInRelapseTumors
        fusionName
        fusionType
        fusionAnno
        gene1AAnno
        gene1BAnno
        gene2AAnno
        gene2BAnno
        genePosition
        geneSymbol
        kinaseDomainRetainedGene1A
        kinaseDomainRetainedGene1B
        MONDO
        PMTL
        reciprocalExistsEitherGeneKinase
        totalPrimaryTumorsMutatedOverPrimaryTumorsInDataset
        totalRelapseTumorsMutatedOverRelapseTumorsInDataset
        annots
        diseaseFromSourceMappedId
        targetFromSourceId
        totalAlterationsOverSubjectsInDataset
        id
        score
      }
    }
  }

  snvByVariant: disease(efoId: "EFO_0000616") {
    id
    evidences(
      ensemblIds: ["ENSG00000171094"]
      enableIndirect: true
      size: 5
      datasourceIds: ["chop_variant_level_snv"]
    ) {
      count
      rows {
        datasourceId
        dataset
        Disease
        frequencyInOverallDataset
        frequencyInPrimaryTumors
        frequencyInRelapseTumors
        geneFullName
        geneSymbol
        hotspot
        MONDO
        OncoKBCancerGene
        OncoKBOncogeneTSG
        polyphenImpact
        proteinEnsemblId
        proteinRefseqId
        proteinChange
        PMTL
        siftImpact
        totalMutationsOverSubjectsInDataset
        totalPrimaryTumorsMutatedOverPrimaryTumorsInDataset
        totalRelapseTumorsMutatedOverRelapseTumorsInDataset
        vepImpact
        variantIdHg38
        variantClassification
        variantType
        dbSNPId
        diseaseFromSourceMappedId
        targetFromSourceId
        id
        score
      }
    }
  }
}
